from .info import NAME, VERSION, DISCORD, REPOSITORY, WIKI, RELEASES, LATEST_RELEASE
from .licenses import LICENSES
from .contributors import CONTRIBUTORS, FEATURE_SUGGESTIONS, SPECIAL_THANKS

class ProjectData:
    NAME: str = NAME
    VERSION: str = VERSION
    DISCORD: str = DISCORD
    REPOSITORY: str = REPOSITORY
    WIKI: str = WIKI
    RELEASES: str = RELEASES
    LATEST_RELEASE: str = LATEST_RELEASE
    LICENSES: list[dict] = LICENSES
    CONTRIBUTORS: list[dict] = CONTRIBUTORS
    FEATURE_SUGGESTIONS: list[dict] = FEATURE_SUGGESTIONS
    SPECIAL_THANKS: list[dict] = SPECIAL_THANKS